//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commun {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commun() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Commun", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conformément aux Conditions Générales d’utilisation de Facebook, dont notamment la Déclaration des Droits et Responsabilités, et conformément à la loi n° 78-17 dite Loi  Informatique et Libertés du 6 janvier 1978 modifiée, les utilisateurs de Facebook fournissent, avec leur accord, les informations personnelles les concernant à l’exploitant de l’application Facebook, [[CLIENT]], en sa qualité de responsable de traitement de données.
        ///Les informations que nous collectons sont nécessaires à exploitation de no [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CharteContent {
            get {
                return ResourceManager.GetString("CharteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Politique d&apos;utilisation des données.
        /// </summary>
        internal static string CharteTitle {
            get {
                return ResourceManager.GetString("CharteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string Fermer {
            get {
                return ResourceManager.GetString("Fermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Imprimer.
        /// </summary>
        internal static string Imprimer {
            get {
                return ResourceManager.GetString("Imprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jeu gratuit sans obligation d&apos;achat..
        /// </summary>
        internal static string Mentionlegale {
            get {
                return ResourceManager.GetString("Mentionlegale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous continuerez à recevoir nos emails..
        /// </summary>
        internal static string OptoutDeleteConfirm {
            get {
                return ResourceManager.GetString("OptoutDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre demande a bien été enregistrée.&lt;br/&gt;Si vous avez cliqué par erreur, &lt;a href=&quot;{0}&quot;&gt;cliquez ici&lt;/a&gt; pour continuer à recevoir nos emails..
        /// </summary>
        internal static string OptoutInsertConfirm {
            get {
                return ResourceManager.GetString("OptoutInsertConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&lt;br/&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ReglementContent {
            get {
                return ResourceManager.GetString("ReglementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Règlement.
        /// </summary>
        internal static string ReglementTitle {
            get {
                return ResourceManager.GetString("ReglementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à InterBook.
        /// </summary>
        internal static string SujetMailContact {
            get {
                return ResourceManager.GetString("SujetMailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici un lien de reconnexion pour le jeu [[nomlong_op]].
        /// </summary>
        internal static string SujetMailRelog {
            get {
                return ResourceManager.GetString("SujetMailRelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à InterBook.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
