//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InterBookEntities : DbContext
    {
        public InterBookEntities()
            : base("name=InterBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ref_Profession> Ref_Profession { get; set; }
        public virtual DbSet<Ref_Ville> Ref_Ville { get; set; }
        public virtual DbSet<Util> Util { get; set; }
        public virtual DbSet<Util_Profession> Util_Profession { get; set; }
        public virtual DbSet<Util_Ville> Util_Ville { get; set; }
    
        public virtual ObjectResult<Util> SearchByVilleProfession(string ville, string profession)
        {
            var villeParameter = ville != null ?
                new ObjectParameter("ville", ville) :
                new ObjectParameter("ville", typeof(string));
    
            var professionParameter = profession != null ?
                new ObjectParameter("profession", profession) :
                new ObjectParameter("profession", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Util>("SearchByVilleProfession", villeParameter, professionParameter);
        }
    }
}
