//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Departement
    {
        public Ref_Departement()
        {
            this.Ref_Ville = new HashSet<Ref_Ville>();
            this.Util_Geo = new HashSet<Util_Geo>();
        }
    
        public string id_Departement { get; set; }
        public string Description { get; set; }
        public Nullable<int> id_Region { get; set; }
    
        public virtual ICollection<Ref_Ville> Ref_Ville { get; set; }
        public virtual Ref_Region Ref_Region { get; set; }
        public virtual ICollection<Util_Geo> Util_Geo { get; set; }
    }
}
