//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Pays
    {
        public Ref_Pays()
        {
            this.Util_Postal = new HashSet<Util_Postal>();
        }
    
        public int id_Pays { get; set; }
        public Nullable<int> codeINSEE { get; set; }
        public Nullable<int> id_Culture { get; set; }
        public string description { get; set; }
    
        public virtual Ref_Culture Ref_Culture { get; set; }
        public virtual ICollection<Util_Postal> Util_Postal { get; set; }
    }
}
