//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Declinaison_Culture
    {
        public Ref_Declinaison_Culture()
        {
            this.Ref_Domaine = new HashSet<Ref_Domaine>();
            this.Ref_From = new HashSet<Ref_From>();
        }
    
        public int id_Declinaison_Culture { get; set; }
        public Nullable<int> id_Declinaison { get; set; }
        public Nullable<int> id_Culture { get; set; }
        public string id_From_Defaut { get; set; }
        public string EmailFromSupport { get; set; }
    
        public virtual Ref_Culture Ref_Culture { get; set; }
        public virtual ICollection<Ref_Domaine> Ref_Domaine { get; set; }
        public virtual ICollection<Ref_From> Ref_From { get; set; }
    }
}
