//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Ville
    {
        public Ref_Ville()
        {
            this.Util_Ville = new HashSet<Util_Ville>();
        }
    
        public int id_Ville { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Util_Ville> Util_Ville { get; set; }
    }
}
