//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Contrat
    {
        public Ref_Contrat()
        {
            this.Util_Contrat = new HashSet<Util_Contrat>();
        }
    
        public int id_Contrat { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Util_Contrat> Util_Contrat { get; set; }
    }
}
