//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Experience
    {
        public Ref_Experience()
        {
            this.Util_Experience = new HashSet<Util_Experience>();
            this.Util_Info = new HashSet<Util_Info>();
        }
    
        public int id_Experience { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Util_Experience> Util_Experience { get; set; }
        public virtual ICollection<Util_Info> Util_Info { get; set; }
    }
}
