//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Profession
    {
        public Ref_Profession()
        {
            this.Util_Profession = new HashSet<Util_Profession>();
        }
    
        public int id_Profession { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Util_Profession> Util_Profession { get; set; }
    }
}
