//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id_Reservation { get; set; }
        public Nullable<int> idUEntreprise { get; set; }
        public Nullable<System.DateTime> debut { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public Nullable<int> id_EtatReservation { get; set; }
        public Nullable<int> idUEmploye { get; set; }
    
        public virtual Util UtilEntreprise { get; set; }
        public virtual Ref_EtatReservation Ref_EtatReservation { get; set; }
        public virtual Util Util { get; set; }
    }
}
