//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UE_envoi
    {
        public int id_UE_envoi { get; set; }
        public Nullable<int> id_mailing { get; set; }
        public Nullable<int> idu_email { get; set; }
        public Nullable<int> idu { get; set; }
        public Nullable<System.DateTime> dEnvoi { get; set; }
    
        public virtual Ref_Mailing Ref_Mailing { get; set; }
        public virtual Util Util { get; set; }
        public virtual Util_Email Util_Email { get; set; }
    }
}
