//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util_Ville
    {
        public int id_Util_Ville { get; set; }
        public Nullable<int> IdU { get; set; }
        public Nullable<int> id_Ville { get; set; }
    
        public virtual Ref_Ville Ref_Ville { get; set; }
        public virtual Util Util { get; set; }
    }
}
