//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util
    {
        public Util()
        {
            this.Util_Profession = new HashSet<Util_Profession>();
            this.Util_Ville = new HashSet<Util_Ville>();
        }
    
        public int IdU { get; set; }
        public Nullable<int> idu_email { get; set; }
    
        public virtual ICollection<Util_Profession> Util_Profession { get; set; }
        public virtual ICollection<Util_Ville> Util_Ville { get; set; }
    }
}
