//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util_Dispo
    {
        public int id_Util_Dispo { get; set; }
        public Nullable<System.DateTime> dDispo { get; set; }
        public Nullable<int> idU { get; set; }
        public Nullable<int> id_Ref_Dispo { get; set; }
    
        public virtual Util Util { get; set; }
        public virtual Ref_Dispo Ref_Dispo { get; set; }
    }
}
