//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util
    {
        public Util()
        {
            this.UE_envoi = new HashSet<UE_envoi>();
            this.Util_Consentement = new HashSet<Util_Consentement>();
            this.Util_Contrat = new HashSet<Util_Contrat>();
            this.Util_Dispo = new HashSet<Util_Dispo>();
            this.Util_Experience = new HashSet<Util_Experience>();
            this.Util_Profession = new HashSet<Util_Profession>();
            this.Util_Ville = new HashSet<Util_Ville>();
        }
    
        public int IdU { get; set; }
        public Nullable<int> id_Declinaison_Culture { get; set; }
        public Nullable<int> id_From { get; set; }
        public string mdp { get; set; }
        public Nullable<System.Guid> uid { get; set; }
        public Nullable<int> idu_Email { get; set; }
        public Nullable<int> idu_Postal { get; set; }
        public Nullable<int> idu_Telmobile { get; set; }
        public Nullable<System.DateTime> dCrea { get; set; }
        public Nullable<System.DateTime> dMAJ { get; set; }
    
        public virtual ICollection<UE_envoi> UE_envoi { get; set; }
        public virtual ICollection<Util_Consentement> Util_Consentement { get; set; }
        public virtual ICollection<Util_Contrat> Util_Contrat { get; set; }
        public virtual ICollection<Util_Dispo> Util_Dispo { get; set; }
        public virtual ICollection<Util_Experience> Util_Experience { get; set; }
        public virtual ICollection<Util_Profession> Util_Profession { get; set; }
        public virtual Util_Email Util_Email { get; set; }
        public virtual Util_Postal Util_Postal { get; set; }
        public virtual ICollection<Util_Ville> Util_Ville { get; set; }
    }
}
