//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util_Info
    {
        public Util_Info()
        {
            this.Utils = new HashSet<Util>();
        }
    
        public int id_Util_Info { get; set; }
        public Nullable<int> photo { get; set; }
        public Nullable<int> cv { get; set; }
        public string numTel { get; set; }
        public Nullable<System.DateTime> dNaissance { get; set; }
        public Nullable<int> experience { get; set; }
        public string motivation { get; set; }
        public Nullable<bool> permisA { get; set; }
        public Nullable<bool> permisB { get; set; }
        public Nullable<bool> permisC { get; set; }
    
        public virtual Ref_Experience Ref_Experience { get; set; }
        public virtual ICollection<Util> Utils { get; set; }
    }
}
