//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util_Geo
    {
        public int id_Util_Geo { get; set; }
        public string id_Departement { get; set; }
        public Nullable<int> id_Region { get; set; }
        public Nullable<int> idU { get; set; }
    
        public virtual Ref_Departement Ref_Departement { get; set; }
        public virtual Ref_Region Ref_Region { get; set; }
        public virtual Util Util { get; set; }
    }
}
