//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterBook2._0.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util_Consentement
    {
        public int id_Util_Consentement { get; set; }
        public Nullable<int> id_TypeConsentement { get; set; }
        public Nullable<int> valeur { get; set; }
        public Nullable<int> id_Mailing { get; set; }
        public Nullable<int> idu { get; set; }
        public Nullable<System.DateTime> dRecueil { get; set; }
    
        public virtual Ref_Mailing Ref_Mailing { get; set; }
        public virtual Ref_TypeConsentement Ref_TypeConsentement { get; set; }
        public virtual Util Util { get; set; }
    }
}
